version: '3.8'

services:
  api_gateway:
    build: .
    container_name: api_gateway
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - medicament
      - fournisseurs
      - ventes
      - utilisateurs
      - rapport
    networks:
      - gateway_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - gateway_network

  medicament:
    image: my_medicament_service
    container_name: medicament
    restart: always
    networks:
      - gateway_network

  fournisseurs:
    image: my_fournisseurs_service
    container_name: fournisseurs
    restart: always
    networks:
      - gateway_network

  ventes:
    image: my_ventes_service
    container_name: ventes
    restart: always
    networks:
      - gateway_network

  utilisateurs:
    image: my_utilisateurs_service
    container_name: utilisateurs
    restart: always
    networks:
      - gateway_network

  rapport:
    image: my_rapport_service
    container_name: rapport
    restart: always
    networks:
      - gateway_network

networks:
  gateway_network:
    driver: bridge
